package it.polito.ai.backend.dtos;

import it.polito.ai.backend.services.exercise.AssignmentStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.hateoas.RepresentationModel;

import javax.persistence.GeneratedValue;
import javax.validation.constraints.NotNull;
import java.sql.Timestamp;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class AssignmentDTO extends RepresentationModel<AssignmentDTO> {
    /**
     * id is the id of an assignment autogenerated
     * pulished is the date when was pulished
     * status is the state, can be NULL, LETTO, CONSEGANTO, RIVISTO
     * falg if true the student che upload an assignemnt, it is set to false when teacher assignet an score
     * score is the score assigned by the teacher
     * imege is an array of byte of the image uploaded
     * */
    @GeneratedValue
    @NotNull
    Long id;
    @NotNull
    Timestamp published;
    AssignmentStatus status;
    @NotNull
    boolean flag;
    Integer score;
    private Byte[] image;
}
